fix: false             # default: false
parallel: true         # default: false
format: progress       # default: Standard::Formatter
ruby_version: 2.6.6    # default: RUBY_VERSION
default_ignores: false  # default: true

ignore:                 # default: []
  - 'bin/*'
  - 'db/schema.rb'
  - 'node_modules/**/*'
  - 'vendor/**/*'
